### ISSUE TITLE
the executable doesn't seem to work for me

### ISSUE THREAD

**Issue by jLn0n** [sten-code/Celery#1]
for some reason when i launch the executable, it just shows nothing, the user interface doesn't show

**Comment by sten-code** [comment]
@jLn0n Do you have the .Net Framework installed? 
It's using [.NET Framework 4.7.2](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472), make sure you're downloading the runtime.

If that doesn't work try downloading the [source code of v1.1.0](https://github.com/sten-code/Celery/tree/1.1.0) and compiling it yourself. You will need [Visual Studio 2022 Community](https://visualstudio.microsoft.com/downloads/) with the `.NET Desktop Environment` workload.

After installing just open the `Celery.sln` file with Visual Studio, set the build type from `Debug` to `Release` and click `Start`. You can see the build of Celery inside `Celery > bin > Release`.

Please let me know if this worked.

**Comment by sten-code** [comment]
Wait nevermind, I completely forgot something in the code. I'm gonna fix it in the new version, it'll be released in a couple minutes.

**Comment by jLn0n** [comment]
> @jLn0n I completely forgot something in the code. I'm gonna fix it in the new version, it'll be released in a couple minutes.
> 
> Edit: Its updated now, please download v1.1.1 and it _should_ be fixed.

thank you very much!!!
